name: React Project
on: [push,workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: action
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: building
        run: npm run build
      - name: test
        run: echo "working"